changelog:
  categories:
    - title: "⚠️ Breaking Changes"
      labels:
        - "breaking"
    - title: "🚀 Features"
      labels:
        - "enhancement"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
    - title: "⚙️ Refactoring"
      labels:
        - "refactor"
    - title: "📚 Documentation"
      labels:
        - "documentation"
    - title: "🔒 Security"
      labels:
        - "security"
    - title: "Other Changes"
      labels:
        - "*"
  exclude:
    labels:
      - "skip-changelog"
