[package]
name = "todo-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tui-textarea = "0.7.0"
unicode-width = "0.2.0"