[package]
name = "todo-tui"
version = "0.2.1"
edition = "2024"

[dependencies]
chrono = "0.4.40"
directories = "6.0.0"
ratatui = "0.29.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tui-textarea = "0.7.0"
